<a href="https://colab.research.google.com/github/saivikaskondamidi/Vikas_data_690/blob/main/world_development_explorer/Part_B_Final/part_b_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Final Project_Data_690**

- Name: Sai Vikas Kondamidi
- Date: 09-04-22

#Data source

 **https://www.worlddev.xyz**



##Topic

Finding Poverty Rate and Literacy rate of South asian countries and North America 

- Gender
- Private Sector
- Health
- Poverty

##Indicators

- Educational attainment, at least completed post-secondary, population 25+, total(%) (cummulative)
- Educational attainment, at least completed primary, population 25+, male(%) (cummulative)
- Educational attainment, at least completed primary, population 25+, female(%) (cummulative)
- Population, total
- Proportion of people living below 50 percent of median income (%)
- Population, male
- Population, female
- Age dependency ratio (% of working-age population)
- Literacy rate,adult male % of males ages 15 and above)
- Literacy rate,adult female % of females ages 15 and above)
- Number of male directors
- Number of female directors

##Countries

- Afghanistan
- Bangladesh
- Bermuda
- Bhutan
- Canada
- India
- Srilanka
- Maldives
- Nepal
- Pakistan
- United States

##Time Span

- 2016-2020

**Introduction**

###WHY THIS TOPIC

- Finding literacy late of north america and south asia region
- Exploring the insights from the indicators
- Finding gender based insights using some trends
- How literacy rate changes following 2 regions
- Finding depedency ration of people in 2 regions
- Finally finding out which country has highest median income comparing 
- population, literacy rate , Age dependency and Gender.


##Why it is important to all

- To understand Literacy rate from given time span
- To know the insights of the countries
- Basic trends of north america and south asia
- To get better knowledge , it is easy after checking out this blog.

##What questions to be answered

- which gender has the highest board directors of the company
- which country has the highest literacy rate
- which country has the highest age dependecy rate
- which country people living below 50 % of median income




##Following step are used to analyze the issues

- Finding the highest and lowest population
- Finding male and female population
- Comparing male and female literacy rate
- Comparing Literacy rate using 2 regions
- Finding which Age dependency ration using 2 regions
- Finally getting which country people has poverty

In [3]:
# Importing Required Libraries
import pandas as pd
import plotly.express as px
import plotly

In [4]:
# Reading CSV File
df = pd.read_csv('https://raw.githubusercontent.com/saivikaskondamidi/Vikas_data_690/main/world_development_explorer/wdi_data-3.csv')
df.head()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,0,2016,60.907581,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
1,1,2017,61.796349,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
2,2,2018,62.488289,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
3,3,2019,64.912209,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
4,4,2020,66.910469,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA

In [5]:
df.tail()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
305,305,2016,51.646167,SP.POP.DPND,USA,United States,North America,High income,Not classified
306,306,2017,52.155806,SP.POP.DPND,USA,United States,North America,High income,Not classified
307,307,2018,52.710677,SP.POP.DPND,USA,United States,North America,High income,Not classified
308,308,2019,53.277666,SP.POP.DPND,USA,United States,North America,High income,Not classified
309,309,2020,53.852481,SP.POP.DPND,USA,United States,North America,High income,Not classified

In [6]:
df['Country Code'].unique()

array(['BGD', 'BTN', 'PAK', 'USA', 'AFG', 'BMU', 'CAN', 'IND', 'MDV',
       'NPL', 'LKA'], dtype=object)

In [7]:
df['Country Name'].unique()

array(['Bangladesh', 'Bhutan', 'Pakistan', 'United States', 'Afghanistan',
       'Bermuda', 'Canada', 'India', 'Maldives', 'Nepal', 'Sri Lanka'],
      dtype=object)

In [8]:
df_Pop = df.query("indicator == 'SP.POP.TOTL' ")
df_Pop

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
13,13,2016,3.538303e+07,SP.POP.TOTL,AFG,Afghanistan,South Asia,Low income,IDA
14,14,2017,3.629611e+07,SP.POP.TOTL,AFG,Afghanistan,South Asia,Low income,IDA
15,15,2018,3.717192e+07,SP.POP.TOTL,AFG,Afghanistan,South Asia,Low income,IDA
16,16,2019,3.804176e+07,SP.POP.TOTL,AFG,Afghanistan,South Asia,Low income,IDA
17,17,2020,3.892834e+07,SP.POP.TOTL,AFG,Afghanistan,South Asia,Low income,IDA
18,18,2016,1.579772e+08,SP.POP.TOTL,BGD,Bangladesh,South Asia,Lower middle income,IDA
19,19,2017,1.596854e+08,SP.POP.TOTL,BGD,Bangladesh,South Asia,Lower middle income,IDA
20,20,2018,1.613767e+08,SP.POP.TOTL,BGD,Bangladesh,South Asia,Lower middle income,IDA
21,21,2019,1.630462e+08,SP.POP.TOTL,BGD,Bangladesh,South Asia,Lower middle income,IDA
22,22,2020,1.646894e+08,SP.POP.TOTL,BGD,Bangladesh,South Asia,Lower middle income,IDA
23,23,2016,6.455400e+04,SP.POP.TOTL,BMU,Bermuda,North America,High income,Not classified
24,24,2017,6.387300e+04,SP.POP.TOTL,BMU,Bermuda,North America,High income,Not classified
25,25,2018,6.391900e+04,SP.POP.TOTL,BMU,Bermuda,North America,High income,Not classified
26,26,2019,6.391300e+04,SP.POP.TOTL,BMU,Bermuda,North America,High income,Not classified
27,27,2020,6.390300e+04,SP.POP.TOTL,BMU,Bermuda,North America,High income,Not classified
28,28,2016,7.367060e+05,SP.POP.TOTL,BTN,Bhutan,South Asia,Lower middle income,IDA
29,29,2017,7.455630e+05,SP.POP.TOTL,BTN,Bhutan,South Asia,Lower middle income,IDA
30,30,2018,7.543960e+05,SP.POP.TOTL,BTN,Bhutan,South Asia,Lower middle income,IDA
31,31,2019,7.630940e+05,SP.POP.TOTL,BTN,Bhutan,South Asia,Lower middle income,IDA
32,32,2020,7.716120e+05,SP.POP.TOTL,BTN,Bhutan,South Asia,Lower middle income,IDA
33,33,2016,3.610949e+07,SP.POP.TOTL,CAN,Canada,North America,High income,Not classified
34,34,2017,3.654530e+07,SP.POP.TOTL,CAN,Canada,North America,High income,Not classified
35,35,2018,3.706518e+07,SP.POP.TOTL,CAN,Canada,North America,High income,Not classified
36,36,2019,3.759338e+07,SP.POP.TOTL,CAN,Canada,North America,High income,Not classified
37,37,2020,3.800524e+07,SP.POP.TOTL,CAN,Canada,North America,High income,Not classified
38,38,2016,1.324517e+09,SP.POP.TOTL,IND,India,South Asia,Lower middle income,IBRD
39,39,2017,1.338677e+09,SP.POP.TOTL,IND,India,South Asia,Lower middle income,IBRD
40,40,2018,1.352642e+09,SP.POP.TOTL,IND,India,South Asia,Lower middle income,IBRD
41,41,2019,1.366418e+09,SP.POP.TOTL,IND,India,South Asia,Lower middle income,IBRD
42,42,2020,1.380004e+09,SP.POP.TOTL,IND,India,South Asia,Lower middle income,IBRD
43,43,2016,4.755050e+05,SP.POP.TOTL,MDV,Maldives,South Asia,Upper middle income,IDA
44,44,2017,4.963980e+05,SP.POP.TOTL,MDV,Maldives,South Asia,Upper middle income,IDA
45,45,2018,5.157040e+05,SP.POP.TOTL,MDV,Maldives,South Asia,Upper middle income,IDA
46,46,2019,5.309570e+05,SP.POP.TOTL,MDV,Maldives,South Asia,Upper middle income,IDA
47,47,2020,5.405420e+05,SP.POP.TOTL,MDV,Maldives,South Asia,Upper middle income,IDA
48,48,2016,2.726343e+07,SP.POP.TOTL,NPL,Nepal,South Asia,Lower middle income,IDA
49,49,2017,2.763268e+07,SP.POP.TOTL,NPL,Nepal,South Asia,Lower middle income,IDA
50,50,2018,2.809571e+07,SP.POP.TOTL,NPL,Nepal,South Asia,Lower middle income,IDA
51,51,2019,2.860872e+07,SP.POP.TOTL,NPL,Nepal,South Asia,Lower middle income,IDA
52,52,2020,2.913681e+07,SP.POP.TOTL,NPL,Nepal,South Asia,Lower middle income,IDA
53,53,2016,2.036314e+08,SP.POP.TOTL,PAK,Pakistan,South Asia,Lower middle income,Blend
54,54,2017,2.079062e+08,SP.POP.TOTL,PAK,Pakistan,South Asia,Lower middle income,Blend
55,55,2018,2.122283e+08,SP.POP.TOTL,PAK,Pakistan,South Asia,Lower middle income,Blend
56,56,2019,2.165653e+08,SP.POP.TOTL,PAK,Pakistan,South Asia,Lower middle income,Blend
57,57,2020,2.208923e+08,SP.POP.TOTL,PAK,Pakistan,South Asia,Lower middle income,Blend
58,58,2016,2.120300e+07,SP.POP.TOTL,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
59,59,2017,2.144400e+07,SP.POP.TOTL,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
60,60,2018,2.167000e+07,SP.POP.TOTL,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
61,61,2019,2.180300e+07,SP.POP.TOTL,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
62,62,2020,2.191900e+07,SP.POP.TOTL,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
63,63,2016,3.230718e+08,SP.POP.TOTL,USA,United States,North America,High income,Not classified
64,64,2017,3.251221e+08,SP.POP.TOTL,USA,United States,North America,High income,Not classified
65,65,2018,3.268382e+08,SP.POP.TOTL,USA,United States,North America,High income,Not classified
66,66,2019,3.283300e+08,SP.POP.TOTL,USA,United States,North America,High income,Not classified
67,67,2020,3.294841e+08,SP.POP.TOTL,USA,United States,North America,High income,Not classified

In [9]:
df_Pop = df.query("Year == 2016").query("indicator == 'SP.POP.TOTL'")

df_Pop_sorted = df_Pop.sort_values(by= "value", ascending= False)
df_Pop_sorted

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
38,38,2016,1.324517e+09,SP.POP.TOTL,IND,India,South Asia,Lower middle income,IBRD
63,63,2016,3.230718e+08,SP.POP.TOTL,USA,United States,North America,High income,Not classified
53,53,2016,2.036314e+08,SP.POP.TOTL,PAK,Pakistan,South Asia,Lower middle income,Blend
18,18,2016,1.579772e+08,SP.POP.TOTL,BGD,Bangladesh,South Asia,Lower middle income,IDA
33,33,2016,3.610949e+07,SP.POP.TOTL,CAN,Canada,North America,High income,Not classified
13,13,2016,3.538303e+07,SP.POP.TOTL,AFG,Afghanistan,South Asia,Low income,IDA
48,48,2016,2.726343e+07,SP.POP.TOTL,NPL,Nepal,South Asia,Lower middle income,IDA
58,58,2016,2.120300e+07,SP.POP.TOTL,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
28,28,2016,7.367060e+05,SP.POP.TOTL,BTN,Bhutan,South Asia,Lower middle income,IDA
43,43,2016,4.755050e+05,SP.POP.TOTL,MDV,Maldives,South Asia,Upper middle income,IDA
23,23,2016,6.455400e+04,SP.POP.TOTL,BMU,Bermuda,North America,High income,Not classified

#Finding which country has the highest and lowest Population by 2020

In [10]:
fig = px.bar(
    data_frame= df_Pop_sorted,
    x= "Country Name",
    labels={"value":"2016 population, total"},
    y= "value",
    color= "Country Name",
    height= 700,
    template=list(plotly.io.templates.keys())[5],
    title= "TOP 10 countries by 2020 population, total"
)

fig.update_layout(showlegend= True)
fig.show()

##Inference

**As we can inference from the above graph we can say that India holds the highest population while Sri lanka holds the least population.**

In [11]:
df_directors = df.query("indicator in(['IC.WEF.LLCD.MA'])")

df_directors

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
68,68,2016,2473.0,IC.WEF.LLCD.MA,AFG,Afghanistan,South Asia,Low income,IDA
69,69,2017,2677.0,IC.WEF.LLCD.MA,AFG,Afghanistan,South Asia,Low income,IDA
70,70,2018,5057.0,IC.WEF.LLCD.MA,AFG,Afghanistan,South Asia,Low income,IDA
71,71,2016,123.0,IC.WEF.LLCD.MA,BTN,Bhutan,South Asia,Lower middle income,IDA
72,72,2017,168.0,IC.WEF.LLCD.MA,BTN,Bhutan,South Asia,Lower middle income,IDA
73,73,2018,127.0,IC.WEF.LLCD.MA,BTN,Bhutan,South Asia,Lower middle income,IDA
74,74,2016,4366.0,IC.WEF.LLCD.MA,NPL,Nepal,South Asia,Lower middle income,IDA
75,75,2017,4850.0,IC.WEF.LLCD.MA,NPL,Nepal,South Asia,Lower middle income,IDA
76,76,2018,6086.0,IC.WEF.LLCD.MA,NPL,Nepal,South Asia,Lower middle income,IDA
77,77,2016,13839.0,IC.WEF.LLCD.MA,PAK,Pakistan,South Asia,Lower middle income,Blend
78,78,2017,18613.0,IC.WEF.LLCD.MA,PAK,Pakistan,South Asia,Lower middle income,Blend
79,79,2018,23572.0,IC.WEF.LLCD.MA,PAK,Pakistan,South Asia,Lower middle income,Blend

In [12]:
df_directors = df.query("Year == 2016").query("indicator == 'IC.WEF.LLCD.MA' ")

df_directors_sorted = df_directors.sort_values(by= "value", ascending= False)
df_directors_sorted

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
77,77,2016,13839.0,IC.WEF.LLCD.MA,PAK,Pakistan,South Asia,Lower middle income,Blend
74,74,2016,4366.0,IC.WEF.LLCD.MA,NPL,Nepal,South Asia,Lower middle income,IDA
68,68,2016,2473.0,IC.WEF.LLCD.MA,AFG,Afghanistan,South Asia,Low income,IDA
71,71,2016,123.0,IC.WEF.LLCD.MA,BTN,Bhutan,South Asia,Lower middle income,IDA

#Finding Male Directors in the Private Sectors using data of 2 regions

In [13]:
fig = px.pie(df_directors_sorted, values='value', names='Country Name', title='2016 number of male directors',template=list(plotly.io.templates.keys())[5])
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.update_layout(showlegend=True)

fig.show()

##Inference

**We can infer from the above Pie Chart that Pakistan Males has the More Directors than any other country**

In [14]:
df_directors1 = df.query("indicator in(['IC.WEF.LLCD.FE'])")

df_directors1

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
80,80,2016,32.0,IC.WEF.LLCD.FE,AFG,Afghanistan,South Asia,Low income,IDA
81,81,2017,34.0,IC.WEF.LLCD.FE,AFG,Afghanistan,South Asia,Low income,IDA
82,82,2018,93.0,IC.WEF.LLCD.FE,AFG,Afghanistan,South Asia,Low income,IDA
83,83,2016,51.0,IC.WEF.LLCD.FE,BTN,Bhutan,South Asia,Lower middle income,IDA
84,84,2017,71.0,IC.WEF.LLCD.FE,BTN,Bhutan,South Asia,Lower middle income,IDA
85,85,2018,45.0,IC.WEF.LLCD.FE,BTN,Bhutan,South Asia,Lower middle income,IDA
86,86,2016,749.0,IC.WEF.LLCD.FE,NPL,Nepal,South Asia,Lower middle income,IDA
87,87,2017,852.0,IC.WEF.LLCD.FE,NPL,Nepal,South Asia,Lower middle income,IDA
88,88,2018,963.0,IC.WEF.LLCD.FE,NPL,Nepal,South Asia,Lower middle income,IDA
89,89,2016,2705.0,IC.WEF.LLCD.FE,PAK,Pakistan,South Asia,Lower middle income,Blend
90,90,2017,3440.0,IC.WEF.LLCD.FE,PAK,Pakistan,South Asia,Lower middle income,Blend
91,91,2018,3950.0,IC.WEF.LLCD.FE,PAK,Pakistan,South Asia,Lower middle income,Blend

In [15]:
df_directors1 = df.query("Year == 2016").query("indicator == 'IC.WEF.LLCD.FE' ")

df_directors1_sorted = df_directors1.sort_values(by= "value", ascending= False)
df_directors1_sorted

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
89,89,2016,2705.0,IC.WEF.LLCD.FE,PAK,Pakistan,South Asia,Lower middle income,Blend
86,86,2016,749.0,IC.WEF.LLCD.FE,NPL,Nepal,South Asia,Lower middle income,IDA
83,83,2016,51.0,IC.WEF.LLCD.FE,BTN,Bhutan,South Asia,Lower middle income,IDA
80,80,2016,32.0,IC.WEF.LLCD.FE,AFG,Afghanistan,South Asia,Low income,IDA

#Finding Female Directors in the Private Sectors using data of 2 regions

In [16]:
fig = px.pie(df_directors1_sorted, values='value', names='Country Name', title='2016 number of female directors',template=list(plotly.io.templates.keys())[5])
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.update_layout(showlegend=True)

fig.show()

##Inference

**Here same the insights we can notice that Pakistan has the highest female directors as well**

In [17]:
df_edu = df.query("indicator in(['SE.PRM.CUAT.MA.ZS'])")

df_edu

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,0,2016,60.907581,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
1,1,2017,61.796349,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
2,2,2018,62.488289,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
3,3,2019,64.912209,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
4,4,2020,66.910469,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
5,5,2017,37.286240,SE.PRM.CUAT.MA.ZS,BTN,Bhutan,South Asia,Lower middle income,IDA
6,6,2016,62.516300,SE.PRM.CUAT.MA.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
7,7,2017,60.432400,SE.PRM.CUAT.MA.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
8,8,2018,47.233971,SE.PRM.CUAT.MA.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
9,9,2019,55.120739,SE.PRM.CUAT.MA.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
10,10,2016,98.855133,SE.PRM.CUAT.MA.ZS,USA,United States,North America,High income,Not classified
11,11,2018,99.081329,SE.PRM.CUAT.MA.ZS,USA,United States,North America,High income,Not classified
12,12,2020,99.020943,SE.PRM.CUAT.MA.ZS,USA,United States,North America,High income,Not classified

In [18]:
df_edu = df.query("Year == 2016").query("indicator == 'SE.PRM.CUAT.MA.ZS'")

df_edu_sorted = df_edu.sort_values(by= "value", ascending= False)
df_edu_sorted

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
10,10,2016,98.855133,SE.PRM.CUAT.MA.ZS,USA,United States,North America,High income,Not classified
6,6,2016,62.516300,SE.PRM.CUAT.MA.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
0,0,2016,60.907581,SE.PRM.CUAT.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA

#Finding Education attainment at least completed primary who are 25+ years , Females

In [19]:

fig = px.bar(
    data_frame= df_edu_sorted,
    x= "Country Name",
    labels={"value":"SE.PRM.CUAT.MA.ZS"},
    y= "value",
    color= "Country Name",
    height= 600,
    template=list(plotly.io.templates.keys())[5],
    title= "Educational attainment by males"
)

fig.update_layout(showlegend= True)
fig.show()

##Inference

**From above we can say that United states males has the highest education attainment comparing with other countries.**

In [20]:
df_edu1 = df.query("indicator in(['SE.PRM.CUAT.FE.ZS'])")

df_edu1

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
102,102,2016,51.647678,SE.PRM.CUAT.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
103,103,2017,53.111622,SE.PRM.CUAT.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
104,104,2018,54.473621,SE.PRM.CUAT.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
105,105,2019,57.316860,SE.PRM.CUAT.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
106,106,2020,58.943359,SE.PRM.CUAT.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
107,107,2017,26.745581,SE.PRM.CUAT.FE.ZS,BTN,Bhutan,South Asia,Lower middle income,IDA
108,108,2016,36.536121,SE.PRM.CUAT.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
109,109,2017,37.677841,SE.PRM.CUAT.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
110,110,2018,30.541140,SE.PRM.CUAT.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
111,111,2019,42.417870,SE.PRM.CUAT.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
112,112,2016,98.897469,SE.PRM.CUAT.FE.ZS,USA,United States,North America,High income,Not classified
113,113,2018,98.985260,SE.PRM.CUAT.FE.ZS,USA,United States,North America,High income,Not classified
114,114,2020,99.088211,SE.PRM.CUAT.FE.ZS,USA,United States,North America,High income,Not classified

In [21]:
df_edu1 = df.query("Year == 2016").query("indicator == 'SE.PRM.CUAT.FE.ZS'")

df_edu1_sorted = df_edu1.sort_values(by= "value", ascending= False)
df_edu1_sorted

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
112,112,2016,98.897469,SE.PRM.CUAT.FE.ZS,USA,United States,North America,High income,Not classified
102,102,2016,51.647678,SE.PRM.CUAT.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
108,108,2016,36.536121,SE.PRM.CUAT.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend

#Finding Education attainment at least completed primary who are 25+ years , Males

In [22]:
fig = px.bar(
    data_frame= df_edu1_sorted,
    x= "Country Name",
    labels={"value":"SE.PRM.CUAT.FE.ZS"},
    y= "value",
    color= "Country Name",
    height= 600,
    template=list(plotly.io.templates.keys())[5],
    title= "Educational attainment by females"
)

fig.update_layout(showlegend= True)
fig.show()

##Inference

**From above we can say that United states females has the highest education attainment comparing with other countries.**

In [23]:
df_lit = df.query("indicator == 'SE.ADT.LITR.MA.ZS'")

df_lit

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
178,178,2016,75.618851,SE.ADT.LITR.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
179,179,2017,75.702362,SE.ADT.LITR.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
180,180,2018,76.669258,SE.ADT.LITR.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
181,181,2019,77.441490,SE.ADT.LITR.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
182,182,2020,77.816711,SE.ADT.LITR.MA.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
183,183,2017,75.019852,SE.ADT.LITR.MA.ZS,BTN,Bhutan,South Asia,Lower middle income,IDA
184,184,2018,82.366707,SE.ADT.LITR.MA.ZS,IND,India,South Asia,Lower middle income,IBRD
185,185,2016,97.298927,SE.ADT.LITR.MA.ZS,MDV,Maldives,South Asia,Upper middle income,IDA
186,186,2018,78.591339,SE.ADT.LITR.MA.ZS,NPL,Nepal,South Asia,Lower middle income,IDA
187,187,2017,71.115997,SE.ADT.LITR.MA.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
188,188,2018,69.276581,SE.ADT.LITR.MA.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
189,189,2019,69.287460,SE.ADT.LITR.MA.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
190,190,2016,93.455887,SE.ADT.LITR.MA.ZS,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
191,191,2017,92.980553,SE.ADT.LITR.MA.ZS,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
192,192,2018,92.772926,SE.ADT.LITR.MA.ZS,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
193,193,2019,93.031357,SE.ADT.LITR.MA.ZS,LKA,Sri Lanka,South Asia,Lower middle income,IBRD

#Finding Literacy rate of adult male who are 15 and above

In [24]:
fig = px.line(
    df_lit,
    x= "Year",
    labels={"value":"Literacy rate,adult male(% of males ages 15 and above)"},
    y= "value",
    height= 700,
    color= "Country Name",
    template=list(plotly.io.templates.keys())[5],
    title= "Literacy rate of adult male"
)

fig.show()

##Inference

**From the above line chart we can say that Srilanka males has the highest Literacy rate comparing with other countries.**

In [25]:
df_lit1 = df.query("indicator == 'SE.ADT.LITR.FE.ZS'")

df_lit1

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
194,194,2016,69.897209,SE.ADT.LITR.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
195,195,2017,70.085701,SE.ADT.LITR.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
196,196,2018,71.181938,SE.ADT.LITR.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
197,197,2019,71.948387,SE.ADT.LITR.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
198,198,2020,72.004784,SE.ADT.LITR.FE.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
199,199,2017,57.083618,SE.ADT.LITR.FE.ZS,BTN,Bhutan,South Asia,Lower middle income,IDA
200,200,2018,65.790810,SE.ADT.LITR.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
201,201,2016,98.114708,SE.ADT.LITR.FE.ZS,MDV,Maldives,South Asia,Upper middle income,IDA
202,202,2018,59.724430,SE.ADT.LITR.FE.ZS,NPL,Nepal,South Asia,Lower middle income,IDA
203,203,2017,46.467670,SE.ADT.LITR.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
204,204,2018,45.398399,SE.ADT.LITR.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
205,205,2019,46.490040,SE.ADT.LITR.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
206,206,2016,91.486107,SE.ADT.LITR.FE.ZS,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
207,207,2017,90.970741,SE.ADT.LITR.FE.ZS,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
208,208,2018,90.795601,SE.ADT.LITR.FE.ZS,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
209,209,2019,91.580872,SE.ADT.LITR.FE.ZS,LKA,Sri Lanka,South Asia,Lower middle income,IBRD

#Finding Literacy rate of adult female who are 15 and above

In [26]:
fig = px.line(
    df_lit1,
    x= "Year",
    labels={"value":"Literacy rate,adult Female(% of females ages 15 and above)"},
    y= "value",
    height= 700,
    color= "Country Name",
    template=list(plotly.io.templates.keys())[5],
    title= "Literacy rate of adult female"
)

fig.show()

##Inference


**From the above line chart we can say that Srilanka females has the highest Literacy rate comparing with other countries.**

In [27]:
df_age = df.query("indicator in(['SP.POP.DPND'])")

df_age

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
260,260,2016,87.941788,SP.POP.DPND,AFG,Afghanistan,South Asia,Low income,IDA
261,261,2017,86.000755,SP.POP.DPND,AFG,Afghanistan,South Asia,Low income,IDA
262,262,2018,84.077655,SP.POP.DPND,AFG,Afghanistan,South Asia,Low income,IDA
263,263,2019,82.109772,SP.POP.DPND,AFG,Afghanistan,South Asia,Low income,IDA
264,264,2020,80.088259,SP.POP.DPND,AFG,Afghanistan,South Asia,Low income,IDA
265,265,2016,51.260019,SP.POP.DPND,BGD,Bangladesh,South Asia,Lower middle income,IDA
266,266,2017,50.091698,SP.POP.DPND,BGD,Bangladesh,South Asia,Lower middle income,IDA
267,267,2018,48.952298,SP.POP.DPND,BGD,Bangladesh,South Asia,Lower middle income,IDA
268,268,2019,47.917434,SP.POP.DPND,BGD,Bangladesh,South Asia,Lower middle income,IDA
269,269,2020,47.018923,SP.POP.DPND,BGD,Bangladesh,South Asia,Lower middle income,IDA
270,270,2016,48.335343,SP.POP.DPND,BTN,Bhutan,South Asia,Lower middle income,IDA
271,271,2017,47.371552,SP.POP.DPND,BTN,Bhutan,South Asia,Lower middle income,IDA
272,272,2018,46.572409,SP.POP.DPND,BTN,Bhutan,South Asia,Lower middle income,IDA
273,273,2019,45.843216,SP.POP.DPND,BTN,Bhutan,South Asia,Lower middle income,IDA
274,274,2020,45.136152,SP.POP.DPND,BTN,Bhutan,South Asia,Lower middle income,IDA
275,275,2016,47.826314,SP.POP.DPND,CAN,Canada,North America,High income,Not classified
276,276,2017,48.616076,SP.POP.DPND,CAN,Canada,North America,High income,Not classified
277,277,2018,49.481877,SP.POP.DPND,CAN,Canada,North America,High income,Not classified
278,278,2019,50.361916,SP.POP.DPND,CAN,Canada,North America,High income,Not classified
279,279,2020,51.239287,SP.POP.DPND,CAN,Canada,North America,High income,Not classified
280,280,2016,50.888137,SP.POP.DPND,IND,India,South Asia,Lower middle income,IBRD
281,281,2017,50.289637,SP.POP.DPND,IND,India,South Asia,Lower middle income,IBRD
282,282,2018,49.775167,SP.POP.DPND,IND,India,South Asia,Lower middle income,IBRD
283,283,2019,49.245242,SP.POP.DPND,IND,India,South Asia,Lower middle income,IBRD
284,284,2020,48.664620,SP.POP.DPND,IND,India,South Asia,Lower middle income,IBRD
285,285,2016,32.634327,SP.POP.DPND,MDV,Maldives,South Asia,Upper middle income,IDA
286,286,2017,31.879746,SP.POP.DPND,MDV,Maldives,South Asia,Upper middle income,IDA
287,287,2018,31.321969,SP.POP.DPND,MDV,Maldives,South Asia,Upper middle income,IDA
288,288,2019,30.805616,SP.POP.DPND,MDV,Maldives,South Asia,Upper middle income,IDA
289,289,2020,30.196810,SP.POP.DPND,MDV,Maldives,South Asia,Upper middle income,IDA
290,290,2016,61.090406,SP.POP.DPND,NPL,Nepal,South Asia,Lower middle income,IDA
291,291,2017,58.733174,SP.POP.DPND,NPL,Nepal,South Asia,Lower middle income,IDA
292,292,2018,56.597291,SP.POP.DPND,NPL,Nepal,South Asia,Lower middle income,IDA
293,293,2019,54.686080,SP.POP.DPND,NPL,Nepal,South Asia,Lower middle income,IDA
294,294,2020,52.993769,SP.POP.DPND,NPL,Nepal,South Asia,Lower middle income,IDA
295,295,2016,66.704803,SP.POP.DPND,PAK,Pakistan,South Asia,Lower middle income,Blend
296,296,2017,66.092145,SP.POP.DPND,PAK,Pakistan,South Asia,Lower middle income,Blend
297,297,2018,65.515202,SP.POP.DPND,PAK,Pakistan,South Asia,Lower middle income,Blend
298,298,2019,64.953313,SP.POP.DPND,PAK,Pakistan,South Asia,Lower middle income,Blend
299,299,2020,64.387741,SP.POP.DPND,PAK,Pakistan,South Asia,Lower middle income,Blend
300,300,2016,52.353631,SP.POP.DPND,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
301,301,2017,52.743300,SP.POP.DPND,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
302,302,2018,53.069553,SP.POP.DPND,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
303,303,2019,53.363100,SP.POP.DPND,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
304,304,2020,53.651625,SP.POP.DPND,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
305,305,2016,51.646167,SP.POP.DPND,USA,United States,North America,High income,Not classified
306,306,2017,52.155806,SP.POP.DPND,USA,United States,North America,High income,Not classified
307,307,2018,52.710677,SP.POP.DPND,USA,United States,North America,High income,Not classified
308,308,2019,53.277666,SP.POP.DPND,USA,United States,North America,High income,Not classified
309,309,2020,53.852481,SP.POP.DPND,USA,United States,North America,High income,Not classified

In [28]:
df_age = df.query("Year == 2020").query("indicator == 'SP.POP.DPND'")

df_age_sorted = df_age.sort_values(by= "value", ascending= False)
df_age_sorted

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
264,264,2020,80.088259,SP.POP.DPND,AFG,Afghanistan,South Asia,Low income,IDA
299,299,2020,64.387741,SP.POP.DPND,PAK,Pakistan,South Asia,Lower middle income,Blend
309,309,2020,53.852481,SP.POP.DPND,USA,United States,North America,High income,Not classified
304,304,2020,53.651625,SP.POP.DPND,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
294,294,2020,52.993769,SP.POP.DPND,NPL,Nepal,South Asia,Lower middle income,IDA
279,279,2020,51.239287,SP.POP.DPND,CAN,Canada,North America,High income,Not classified
284,284,2020,48.664620,SP.POP.DPND,IND,India,South Asia,Lower middle income,IBRD
269,269,2020,47.018923,SP.POP.DPND,BGD,Bangladesh,South Asia,Lower middle income,IDA
274,274,2020,45.136152,SP.POP.DPND,BTN,Bhutan,South Asia,Lower middle income,IDA
289,289,2020,30.196810,SP.POP.DPND,MDV,Maldives,South Asia,Upper middle income,IDA

#Finding Age dependency ratio(%) of working population

In [29]:
fig = px.bar(
    data_frame= df_age_sorted,
    x= "Country Name",
    labels={"value":"2016 Age dependency ratio (% of working-age, population), total"},
    y= "value",
    color= "Country Name",
    height= 700,
    template=list(plotly.io.templates.keys())[5],
    title= "Top Countries which are age dependent"
)

fig.update_layout(showlegend= True)
fig.show()

##Inference
**Afghanistan has the highest ration which has dependency of working population**

In [30]:
df_prop = df.query("indicator in(['SI.DST.50MD'])")

df_prop

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
92,92,2016,6.1,SI.DST.50MD,BGD,Bangladesh,South Asia,Lower middle income,IDA
93,93,2017,13.8,SI.DST.50MD,BTN,Bhutan,South Asia,Lower middle income,IDA
94,94,2016,12.7,SI.DST.50MD,CAN,Canada,North America,High income,Not classified
95,95,2017,13.2,SI.DST.50MD,CAN,Canada,North America,High income,Not classified
96,96,2016,9.7,SI.DST.50MD,MDV,Maldives,South Asia,Upper middle income,IDA
97,97,2018,4.4,SI.DST.50MD,PAK,Pakistan,South Asia,Lower middle income,Blend
98,98,2016,9.7,SI.DST.50MD,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
99,99,2016,18.0,SI.DST.50MD,USA,United States,North America,High income,Not classified
100,100,2017,18.2,SI.DST.50MD,USA,United States,North America,High income,Not classified
101,101,2018,18.2,SI.DST.50MD,USA,United States,North America,High income,Not classified

In [31]:
df_prop = df.query("Year == 2016").query("indicator == 'SI.DST.50MD'")

df_prop_sorted = df_prop.sort_values(by= "value", ascending= False)
df_prop_sorted

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
99,99,2016,18.0,SI.DST.50MD,USA,United States,North America,High income,Not classified
94,94,2016,12.7,SI.DST.50MD,CAN,Canada,North America,High income,Not classified
96,96,2016,9.7,SI.DST.50MD,MDV,Maldives,South Asia,Upper middle income,IDA
98,98,2016,9.7,SI.DST.50MD,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
92,92,2016,6.1,SI.DST.50MD,BGD,Bangladesh,South Asia,Lower middle income,IDA

#Finding which country has the highest Proprotion of people living below 50% of median income (%) from all the above insights

In [32]:
fig = px.pie(df_prop_sorted, values='value', names='Country Name', title='2016 proportion of living below 50 percent of median income %',template=list(plotly.io.templates.keys())[5])
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.update_layout(showlegend=True)

fig.show()

#Conclusion 

From all the insights which i have drawn , i can say that , Though United states people has more literacy rate and it has the second highest population i can say that it has the more people who are living 50 percent of median income by 2020. As we can also see that bangladesh has also has the good literacy rate but its struggling with the poverty.